export const ADD_RECIPE = 'ADD_RECIPE';
export const FETCH_RECIPES = 'FETCH_RECIPES';
export const SET_RECIPES = 'SET_RECIPES';

export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';